services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3334:3334
    volumes:
      - .:/home/node/app
    networks:
      - api-correct_correct_net
  
networks:
  api-correct_correct_net:
    external: true
